[hooks]
dynamic_quotes = 10
collections-import-rewrite = 20
reformat-generics = 40
noqa-reformat = 60
ellipsis-reformat = 70
squish_stubs = 80

[config]
indent = "\t"
line_length = 115

[hooks.yapf]
priority = 30

[hooks.isort]
priority = 50

[hooks.yapf.kwargs]
yapf_style = ".style.yapf"

[hooks.isort.kwargs]
indent = "\t\t"
multi_line_output = 8
import_heading_stdlib = "stdlib"
import_heading_thirdparty = "3rd party"
import_heading_firstparty = "this package"
import_heading_localfolder = "this package"
balanced_wrapping = false
lines_between_types = 0
use_parentheses = true
remove_redundant_aliases = true
default_section = "THIRDPARTY"
known_third_party = [
    "alabaster",
    "apeye",
    "appdirs",
    "attrs",
    "autodocsumm",
    "babel",
    "beautifulsoup4",
    "cachecontrol",
    "certifi",
    "chardet",
    "click",
    "coincidence",
    "colorama",
    "consolekit",
    "coverage",
    "coverage_pyver_pragma",
    "css_parser",
    "deprecation",
    "deprecation_alias",
    "dict2css",
    "docutils",
    "domdf_python_tools",
    "filelock",
    "html5lib",
    "idna",
    "imagesize",
    "importlib_metadata",
    "jinja2",
    "lockfile",
    "markupsafe",
    "mistletoe",
    "msgpack",
    "natsort",
    "packaging",
    "pluggy",
    "py",
    "pydash",
    "pygments",
    "pyparsing",
    "pytest",
    "pytest_cov",
    "pytest_datadir",
    "pytest_randomly",
    "pytest_regressions",
    "pytest_timeout",
    "pytz",
    "pyyaml",
    "requests",
    "requests_file",
    "ruamel_yaml",
    "ruamel_yaml_clib",
    "six",
    "snowballstemmer",
    "soupsieve",
    "sphinx",
    "sphinx_autodoc_typehints",
    "sphinx_prompt",
    "sphinx_tabs",
    "sphinx_toolbox",
    "sphinxcontrib_applehelp",
    "sphinxcontrib_devhelp",
    "sphinxcontrib_htmlhelp",
    "sphinxcontrib_jsmath",
    "sphinxcontrib_qthelp",
    "sphinxcontrib_serializinghtml",
    "tabulate",
    "tldextract",
    "toml",
    "typing_extensions",
    "urllib3",
    "webencodings",
    "zipp",
]
known_first_party = "sphinx_debuginfo"
